# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67422e2adf90889144613f77bb22e1d2586f4bf049adc4a646183b965e678c58fea0b8773b2bc03932092b9c49912907ad18281add5a1ebf329c5e714680a708

test:
  secret_key_base: 0084741afb64f19b3d82fd4e96007746ef5937f291532e1d14dfebb7e0944f68dcf0ebe8f1b139113cbac3752523da105070edb04c3a34fb2c256c9ac7ac627f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
